# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bfc17aaf05334dd88f5407678778fbc5b65a2b75059535d1e7ad94c61c13389564b3ea02a80f0e50cc4632218eee18e6e6f3b8d6da292d9895724aae73d2ee0

test:
  secret_key_base: 13e908081fbb89b220890f060c741155fb22dd95524e48d292fd685fd465eef223f593c403443bc0225f35d3d0bea43f460da25b0364ff972cb10cab7cba8f93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
